version: '3.6'

services:

  contacts:

    build: tools/contacts
    image: varilink/data/contacts
    volumes:
      # app
      - ./tools/contacts/app.pl:/usr/local/src/app.pl
      - ./app/data-app/pm:/usr/local/lib/site_perl
      # configuration
      - ./tools/contacts/app.cfg:/usr/local/etc/app.cfg
      - ./data-int/:/int/
      # data
      - database:/database

  pod2markdown:

    build: tools/pod2markdown
    image: varilink/pod2markdown
    user: "1000:1000"
    command:
      - -c
      - |-
        rm -rf /app/pod2markdown/*
        for ext in pl pm psgi
        do
          for fname in `find /app/$$ext/ -type f -name "*.$$ext"`
          do
            basename=`basename $$fname .$$ext`
            reldir=`dirname $$fname | cut -c6-`
            mkdir -p "/app/pod2markdown/$$reldir/$$basename"
            pod2markdown $$fname > "/app/pod2markdown/$$reldir/$$basename/README.md"
          done
        done
    volumes:
      - ./app/data-app:/app
